#!/usr/bin/env python3
"""
Bright Saplings Daycare — build script
==========================================

Everything is edited in ONE place: the files under src/.
This script stitches those parts back together into the files a browser
(or WordPress) actually loads.

    python3 build.py

Outputs
-------
  index.html                          <- src/_layout-top.html
                                         + src/sections/*.html
                                         + src/_layout-bottom.html
  css/style.css                       <- src/css/*.css, in BUILD_ORDER
  wordpress/bright-saplings/
      assets/css/style.css            <- same bundle
      assets/css/part-*.css           <- the individual part files
      assets/fonts/*.woff2            <- copy of fonts/
      assets/js/script.js             <- copy of js/script.js
      template-parts/section-*.php    <- one per HTML section

Nothing here is required to view the site — index.html and css/style.css are
already built and committed. Run this only after editing something in src/.
"""

import os
import re
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, 'src')
THEME = os.path.join(ROOT, 'wordpress', 'bright-saplings')

# Order matters: tokens first, then base, then components, then sections.
BUILD_ORDER = [
    '00-tokens.css',
    '01-base.css',
    '02-layout.css',
    '03-typography.css',
    '04-buttons.css',
    '05-image-placeholders.css',
    '06-cards.css',
    'sections/header.css',
    'sections/hero.css',
    'sections/about.css',
    'sections/story.css',
    'sections/programs.css',
    'sections/activities.css',
    'sections/food.css',
    'sections/location.css',
    'sections/contact.css',
    'sections/footer.css',
    '07-animations.css',
]

BANNER = '/* ' + '=' * 74 + ' */'


def section_files():
    """src/sections/NN-slug.html in numeric order."""
    d = os.path.join(SRC, 'sections')
    names = sorted(f for f in os.listdir(d) if f.endswith('.html'))
    return [(n, os.path.join(d, n)) for n in names]


def slug_of(name):
    return re.sub(r'^\d+-', '', name).replace('.html', '')


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)
    print('  ->', os.path.relpath(path, ROOT))


# ---------------------------------------------------------------- index.html
def build_html():
    print('index.html')
    out = [read(os.path.join(SRC, '_layout-top.html')).rstrip(), '']

    for name, path in section_files():
        slug = slug_of(name)
        body = read(path).rstrip()
        out.append(body)
        out.append('')
        # <main> wraps everything between the header and the footer
        if slug == 'header':
            out.append('<main id="main">')
            out.append('')
        if slug == 'contact':
            out.append('</main>')
            out.append('')

    # 12-footer.html sorts last, so it lands after </main> — which is right.
    out.append(read(os.path.join(SRC, '_layout-bottom.html')).rstrip())
    out.append('')

    write(os.path.join(ROOT, 'index.html'), '\n'.join(out))


# --------------------------------------------------------------- css/style.css
def build_css():
    print('css/style.css')
    parts = [
        '/* ' + '=' * 74,
        '   LITTLE SPROUTS HOME DAYCARE — built stylesheet',
        '',
        '   GENERATED by build.py. Do not edit this file directly —',
        '   edit the matching file in src/css/ and re-run the build.',
        '   ' + '=' * 74 + ' */',
        '',
    ]
    for rel in BUILD_ORDER:
        path = os.path.join(SRC, 'css', rel)
        if not os.path.exists(path):
            raise SystemExit('missing CSS part: ' + rel)
        parts.append('/* >>> src/css/%s */' % rel)
        parts.append(read(path).strip())
        parts.append('')
    css = '\n'.join(parts)
    write(os.path.join(ROOT, 'css', 'style.css'), css)
    return css


# -------------------------------------------------------------- WordPress copy
def build_theme(css):
    print('wordpress/bright-saplings')

    # bundled + individual stylesheets.
    # Parts live alongside the bundle, not in a subfolder, so the
    # "../fonts/" in the @font-face block resolves the same way from
    # either one.
    write(os.path.join(THEME, 'assets', 'css', 'style.css'), css)
    for rel in BUILD_ORDER:
        flat = 'part-' + rel.replace('sections/', 'section-')
        shutil.copyfile(os.path.join(SRC, 'css', rel),
                        _ensure(os.path.join(THEME, 'assets', 'css', flat)))
    print('  ->', 'wordpress/bright-saplings/assets/css/part-*.css (%d files)' % len(BUILD_ORDER))

    # fonts — the theme must be self-contained too
    font_dir = os.path.join(ROOT, 'fonts')
    for f in sorted(os.listdir(font_dir)):
        if f.endswith('.woff2'):
            shutil.copyfile(os.path.join(font_dir, f),
                            _ensure(os.path.join(THEME, 'assets', 'fonts', f)))
    print('  ->', 'wordpress/bright-saplings/assets/fonts/')

    # javascript
    shutil.copyfile(os.path.join(ROOT, 'js', 'script.js'),
                    _ensure(os.path.join(THEME, 'assets', 'js', 'script.js')))
    print('  ->', 'wordpress/bright-saplings/assets/js/script.js')

    # template parts — the header and footer live in header.php / footer.php
    for name, path in section_files():
        slug = slug_of(name)
        if slug in ('header', 'footer'):
            continue
        body = read(path).rstrip()
        php = (
            "<?php\n"
            "/**\n"
            " * Section: %s\n"
            " *\n"
            " * GENERATED by build.py from src/sections/%s — edit that file,\n"
            " * then re-run `python3 build.py` from the project root.\n"
            " *\n"
            " * @package BrightSaplings\n"
            " */\n"
            "if ( ! defined( 'ABSPATH' ) ) { exit; }\n"
            "?>\n\n%s\n"
        ) % (slug.title(), name, body)
        write(os.path.join(THEME, 'template-parts', 'section-%s.php' % slug), php)


def sync_theme_css_list():
    """Rewrite bright_saplings_css_parts() in functions.php from BUILD_ORDER.

    This used to be a hand-kept list, and it drifted the moment a CSS
    part was added or removed — the theme would silently load a
    stylesheet that no longer existed and skip one that did. Generating
    it means the two can never disagree again.
    """
    path = os.path.join(THEME, 'functions.php')
    if not os.path.exists(path):
        return
    src = open(path, encoding='utf-8').read()
    names = [f[:-4].replace('sections/', 'section-') for f in BUILD_ORDER]
    body = '\n'.join("\t\t'%s'," % n for n in names)
    new = "bright_saplings_css_parts() {\n\treturn array(\n%s\n\t);" % body
    start = src.find('bright_saplings_css_parts() {')
    if start == -1:
        return
    end = src.find(');', start) + 2
    src = src[:start] + new + src[end:]
    open(path, 'w', encoding='utf-8').write(src)
    print('  ->', 'wordpress/bright-saplings/functions.php (%d css parts)' % len(names))


def _ensure(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return path


if __name__ == '__main__':
    build_html()
    css = build_css()
    build_theme(css)
    sync_theme_css_list()
    print('\nDone.')
