<?php
/**
 * Section: Location
 *
 * GENERATED by build.py from src/sections/08-location.html — edit that file,
 * then re-run `python3 build.py` from the project root.
 *
 * @package BrightSaplings
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>

<!-- ============================================================
     SECTION: Location
     Needs: src/css/sections/location.css
     ============================================================ -->
<section class="section section--blush" id="location">
  <div class="wrap location">

    <div class="reveal">
      <span class="sticker sticker--peach">Finding us</span>
      <h2 class="about__statement">Conveniently placed for families around Bothell.</h2>

      <p class="lede">
        We're a home program in a quiet residential neighborhood, minutes from
        the 527 and easy to reach on the way to work.
      </p>

      <ul class="loc-facts">
        <li>
          <span class="lbl">Area</span>
          <span class="val">Bothell, WA
            <em>The exact address is shared once your tour is confirmed. It is a family home.</em>
          </span>
        </li>
        <li>
          <span class="lbl">Hours</span>
          <span class="val">8:00am to 6:00pm
            <em>Monday to Friday. Full-day care with a healthy balance of learning and play.</em>
          </span>
        </li>
        <li>
          <span class="lbl">Ages</span>
          <span class="val">18 months to 5 years
            <em>Caring for toddlers and preschoolers.</em>
          </span>
        </li>
        <li>
          <span class="lbl">Phone</span>
          <span class="val"><a href="tel:+14254289660">425-428-9660</a>
            <em>Call or text, whichever is easier.</em>
          </span>
        </li>
      </ul>
    </div>

    <div class="reveal reveal--delay">
      <figure class="frame">
        <!-- IMAGE: drop a Google Maps screenshot in as images/map.jpg,
             or replace this whole <figure> with a Maps embed iframe. -->
        <div class="img-ph img-ph--map" aria-hidden="true">
          <span class="img-ph__label">Map placeholder</span>
          <span class="img-ph__hint">images/map.jpg, or a Google Maps embed</span>
        </div>
        <figcaption>minutes off the 527</figcaption>
      </figure>
    </div>

  </div>
</section>
