<?php
/**
 * Section: Story
 *
 * GENERATED by build.py from src/sections/04-story.html — edit that file,
 * then re-run `python3 build.py` from the project root.
 *
 * @package BrightSaplings
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>

<!-- ============================================================
     SECTION: Our story — Pooja Agarwal
     Needs: src/css/sections/story.css

     ┌──────────────────────────────────────────────────────────┐
     │  THIS IS A TEMPLATE. NOTHING HERE IS INVENTED.           │
     │                                                          │
     │  An earlier draft made up a city, a year and the         │
     │  children's ages to make the story read well. That was   │
     │  wrong — it is a real person's life. Every made-up fact  │
     │  has been taken out.                                     │
     │                                                          │
     │  What is left is true, and it reads finished. The page   │
     │  can go live exactly as it is.                           │
     │                                                          │
     │  Everything we know: Pooja Agarwal, came from India with │
     │  her husband and two children — an older daughter and a  │
     │  son — and ran Sugar n Flakes Bakery & Cafe before       │
     │  opening Bright Saplings.                                │
     │                                                          │
     │  WHEN POOJA SENDS HER DETAILS, the slots are marked      │
     │  ⟨LIKE THIS⟩ in the comments below. Each one says what   │
     │  to ask and where the answer goes. Nothing breaks if a   │
     │  slot is left alone.                                     │
     └──────────────────────────────────────────────────────────┘
     ============================================================ -->
<section class="section section--sage story" id="story">
  <div class="wrap">

    <div class="head head--wide reveal">
      <span class="sticker sticker--tang">Our story</span>
      <h2>It started with her own two.</h2>
    </div>

    <div class="story__grid">

      <!-- ================= PHOTOS ================= -->
      <div class="story__media">

        <figure class="frame reveal" style="--rot:-2deg">
          <img class="img-real img-real--portrait" src="images/story-photo-1.jpg"
               alt="Two young children sitting together, the older girl with both arms around the younger boy"
               width="900" height="1221" loading="lazy" decoding="async">
          <!-- ⟨CAPTION 1⟩ Ask Pooja what she'd like this to say. Something
               plain and true works best — a place, or a year, or nothing
               more than what's happening in the picture. -->
          <figcaption>the two who started all this</figcaption>
        </figure>

        <figure class="frame frame--sm reveal reveal--delay" style="--rot:2.6deg">
          <img class="img-real img-real--portrait" src="images/story-photo-2.jpg"
               alt="A young girl in a yellow t-shirt smiling at the camera"
               width="760" height="962" loading="lazy" decoding="async">
          <!-- ⟨CAPTION 2⟩ Same again. -->
          <figcaption>before any of it had a name</figcaption>
        </figure>

        <div class="story__card">
          <span class="story__card-label">Founder</span>
          <strong>Pooja Agarwal</strong>
          <span>Baker, mother of two,<br>and the reason this house is loud</span>
        </div>

      </div>

      <!-- ================= THE STORY ================= -->
      <div class="story__copy">

        <p class="lede reveal">
          Pooja Agarwal came here from India with her husband and two small
          children: a daughter, and a son a few years behind her.
          Everything Bright Saplings is now started in that house, long before
          it had a name.
          <!-- ⟨WHERE AND WHEN⟩ If Pooja is happy to say, this is the natural
               place for it: "…came here from ⟨CITY⟩ in ⟨YEAR⟩ with…" -->
        </p>

        <div class="story__beats stagger">

          <div class="beat">
            <span class="beat__mark" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12h20M12 2a15 15 0 0 1 0 20M12 2a15 15 0 0 0 0 20"/><circle cx="12" cy="12" r="10"/></svg>
            </span>
            <h3>Starting over</h3>
            <p>
              A new country is a quiet place at first. There is a school run to
              work out, a house that doesn't smell like home yet, and a very
              small person holding your hand who is also working it all out.
              <!-- ⟨THE ARRIVAL⟩ The one detail worth asking for. What was the
                   hardest part of the first year? One specific thing — a
                   school gate, a phone call, a winter — beats a paragraph
                   of general feeling. -->
            </p>
          </div>

          <div class="beat">
            <span class="beat__mark" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M5 21h14M6 21v-6a6 6 0 0 1 12 0v6"/><path d="M9 6c0-1.5 1-2 1-3M13 6c0-1.5 1-2 1-3"/></svg>
            </span>
            <h3>So she baked</h3>
            <p>
              It was the thing that made the house feel like hers. Then
              neighbors started asking, and friends of neighbors after that.
              <!-- ⟨WHAT SHE BAKED⟩ Names of two or three actual things would
                   land beautifully here. -->
            </p>
          </div>

          <div class="beat">
            <span class="beat__mark" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9h18l-1.5 11.5a1.5 1.5 0 0 1-1.5 1.3H6a1.5 1.5 0 0 1-1.5-1.3Z"/><path d="M3 9 5 4h14l2 5"/><path d="M9.5 13v4M14.5 13v4"/></svg>
            </span>
            <h3>Sugar n Flakes Bakery &amp; Cafe</h3>
            <p>
              The asking turned into a store. Years of it: early mornings, real
              ingredients, and learning exactly how much a small person will
              actually eat.
              <!-- ⟨THE BAKERY⟩ Worth having: the year it opened, and where.
                   If it's still trading, say so — it's a credential. -->
            </p>
          </div>

          <div class="beat">
            <span class="beat__mark" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20.8 8.6a5 5 0 0 0-8.8-2.6 5 5 0 0 0-8.8 2.6C3.2 13.6 12 19 12 19s8.8-5.4 8.8-10.4Z"/></svg>
            </span>
            <h3>And then the children</h3>
            <p>
              What she hadn't planned for was who a warm room fills up with.
              Parents, and their children, and the slow realization that the
              part of the day she looked forward to was the small people at the
              table, not the counter.
              <!-- ⟨THE TURNING POINT⟩ The most important question to ask her:
                   what was the moment she decided to open a daycare? -->
            </p>
          </div>

        </div>

        <blockquote class="story__quote reveal">
          <p>
            A child should be somewhere they are known by name, fed properly, and
            allowed to take their time. That is the whole idea.
          </p>
          <cite>Bright Saplings</cite>
          <!-- ⟨HER WORDS⟩ This is the house's promise, not a quote from Pooja —
               we are not putting words in her mouth. When she sends a line of
               her own, paste it above and change the <cite> to her name. -->
        </blockquote>

        <p class="reveal">
          Bright Saplings is the same person, the same kitchen and the same
          standards, in a house built around children rather than a counter. Her
          daughter and son are older now, and both still get roped in when
          there's baking to do.
        </p>

        <a class="link-arrow" href="#contact">
          Come and meet her
          <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8h10M9 4l4 4-4 4"/></svg>
        </a>

      </div>
    </div>

  </div>
</section>
