<?php
/**
 * Section: Contact
 *
 * GENERATED by build.py from src/sections/09-contact.html — edit that file,
 * then re-run `python3 build.py` from the project root.
 *
 * @package BrightSaplings
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>

<!-- ============================================================
     SECTION: Contact
     Needs: src/css/sections/contact.css
     ============================================================ -->
<section class="section" id="contact">
  <div class="wrap contact">

    <div class="contact__info reveal">
      <h2 class="about__statement">Come and see it in person.</h2>

      <p class="lede">
        The quickest way to know whether a place is right for your child is to
        stand in it for ten minutes. Reach us by phone or text, or send the form,
        and we'll find a time.
      </p>

      <a class="phone-big" href="tel:+14254289660">
        <span class="phone-big__icon" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2Z"/>
          </svg>
        </span>
        425-428-9660
      </a>

      <ul class="contact-list">
        <li>
          <span class="contact-list__label">Hours</span>
          <span>Monday to Friday, 8:00am to 6:00pm
            <em>Closed weekends and major holidays.</em>
          </span>
        </li>
        <li>
          <span class="contact-list__label">Ages</span>
          <span>18 months to 5 years
            <em>Toddlers and preschoolers, full day.</em>
          </span>
        </li>
        <li>
          <span class="contact-list__label">Where</span>
          <span>Bothell, WA
            <em>Exact address shared once your tour is confirmed.</em>
          </span>
        </li>
        <li>
          <span class="contact-list__label">Tuition</span>
          <span>Ask us for current rates
            <em>Rates depend on your child's age and the days you need.</em>
          </span>
        </li>
      </ul>
    </div>

    <div class="contact__form-wrap reveal reveal--delay">
      <form class="form" id="tourForm" novalidate>
        <h3 class="form__title">Book a tour</h3>
        <p class="form__note">We reply within one business day</p>

        <div class="field">
          <label for="parentName">Your name <span aria-hidden="true">*</span></label>
          <input type="text" id="parentName" name="parentName" autocomplete="name" required>
          <p class="field__error" data-error-for="parentName"></p>
        </div>

        <div class="field-row">
          <div class="field">
            <label for="email">Email <span aria-hidden="true">*</span></label>
            <input type="email" id="email" name="email" autocomplete="email" required>
            <p class="field__error" data-error-for="email"></p>
          </div>
          <div class="field">
            <label for="phone">Phone</label>
            <input type="tel" id="phone" name="phone" autocomplete="tel">
            <p class="field__error" data-error-for="phone"></p>
          </div>
        </div>

        <div class="field-row">
          <div class="field">
            <label for="childAge">Child's age</label>
            <select id="childAge" name="childAge">
              <option value="">Select one</option>
              <option>Not yet 18 months</option>
              <option>18 months &ndash; 2 years</option>
              <option>2 &ndash; 3 years</option>
              <option>3 &ndash; 4 years</option>
              <option>4 &ndash; 5 years</option>
            </select>
          </div>
          <div class="field">
            <label for="startDate">Ideal start date</label>
            <input type="date" id="startDate" name="startDate">
          </div>
        </div>

        <fieldset class="field field--days">
          <legend>Days needed</legend>
          <div class="chip-group">
            <label class="chip"><input type="checkbox" name="days" value="Mon"><span>Mon</span></label>
            <label class="chip"><input type="checkbox" name="days" value="Tue"><span>Tue</span></label>
            <label class="chip"><input type="checkbox" name="days" value="Wed"><span>Wed</span></label>
            <label class="chip"><input type="checkbox" name="days" value="Thu"><span>Thu</span></label>
            <label class="chip"><input type="checkbox" name="days" value="Fri"><span>Fri</span></label>
          </div>
        </fieldset>

        <div class="field">
          <label for="message">Anything we should know?</label>
          <textarea id="message" name="message" rows="4" placeholder="Allergies, schedule questions, anything at all&hellip;"></textarea>
        </div>

        <button class="btn btn--peach btn--block" type="submit">Send request</button>

        <p class="form__status" id="formStatus" role="status" aria-live="polite"></p>

        <!-- NOTE: frontend only. To make this send, point the form at Formspree
             or a form plugin — see the handler in js/script.js. -->
        <p class="form__fineprint">
          By sending this you agree we may contact you about enrollment. We never
          share your information with anyone.
        </p>
      </form>
    </div>

  </div>
</section>
