<?php
/**
 * Section: About
 *
 * GENERATED by build.py from src/sections/03-about.html — edit that file,
 * then re-run `python3 build.py` from the project root.
 *
 * @package BrightSaplings
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>

<!-- ============================================================
     SECTION: About us + what we offer
     Needs: src/css/sections/about.css
     ============================================================ -->
<section class="section" id="about">
  <div class="wrap about">

    <div class="about__media reveal">
      <figure class="frame">
        <!-- IMAGE: images/about.jpg (1200x1400) -->
        <div class="img-ph img-ph--portrait" aria-hidden="true">
          <span class="img-ph__label">About photo</span>
          <span class="img-ph__hint">images/about.jpg &middot; 1200&times;1400</span>
        </div>
        <figcaption>our front room, mid-morning</figcaption>
      </figure>
      <div class="about__badge">
        <span class="num">8&ndash;6</span>
        <span>full-day care,<br>Monday to Friday</span>
      </div>
    </div>

    <div class="about__copy reveal reveal--delay">
      <h2 class="about__statement">
        A warm, home-like place where little hearts grow &amp; bright futures blossom.
      </h2>

      <p class="lede">
        Bright Saplings is a licensed in-home daycare in Bothell for toddlers and
        preschoolers, 18&nbsp;months to 5&nbsp;years. Nurturing today, inspiring
        tomorrow.
      </p>
      <p>
        We keep our groups small on purpose. It means every child is known by
        name, every parent gets a real conversation at pickup, and the day can
        bend around a child who needs a little longer with something.
      </p>

      <h3 class="visually-hidden">What makes us special</h3>
      <ul class="offer">
        <li>
          <span class="offer__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20V10l8-6 8 6v10"/><path d="M4 20h16M10 20v-5h4v5"/></svg>
          </span>
          <h3>A warm, home-like environment</h3>
          <p>Where children feel safe, loved and supported. A second home, not an institution.</p>
        </li>
        <li>
          <span class="offer__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 5h7a3 3 0 0 1 3 3v11a2.5 2.5 0 0 0-2.5-2.5H3Z"/><path d="M21 5h-7a3 3 0 0 0-3 3v11a2.5 2.5 0 0 1 2.5-2.5H21Z"/></svg>
          </span>
          <h3>Play-based learning</h3>
          <p>Building confidence, curiosity and a genuine love for learning, not worksheets.</p>
        </li>
        <li>
          <span class="offer__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20a7 7 0 0 0 7-7V8a7 7 0 0 0-14 0v5a7 7 0 0 0 7 7Z"/><path d="M12 4V2M9.5 8.5h5"/></svg>
          </span>
          <h3>Nutritious meals and snacks</h3>
          <p>Cooked here every morning by a trained baker, with allergies taken seriously.</p>
        </li>
        <li>
          <span class="offer__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="3.5"/><path d="M19 20v-2a4 4 0 0 0-3-3.9"/><path d="M15 3.6a4 4 0 0 1 0 6.8"/></svg>
          </span>
          <h3>Small class sizes</h3>
          <p>Personalized care and meaningful attention, every day, for every child.</p>
        </li>
        <li>
          <span class="offer__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.8 8.6a5 5 0 0 0-8.8-2.6 5 5 0 0 0-8.8 2.6C3.2 13.6 12 19 12 19s8.8-5.4 8.8-10.4Z"/></svg>
          </span>
          <h3>Social-emotional development</h3>
          <p>Helping children grow kind, confident and independent. That is the part that lasts.</p>
        </li>
        <li>
          <span class="offer__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M19.1 4.9 17 7M7 17l-2.1 2.1"/></svg>
          </span>
          <h3>Daily outdoor play</h3>
          <p>Time outside every day it's safe, to support active, healthy little bodies.</p>
        </li>
      </ul>

      <a class="link-arrow" href="#contact">
        Come and see the place
        <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8h10M9 4l4 4-4 4"/></svg>
      </a>
    </div>

  </div>
</section>
