<?php
/**
 * Section: Activities
 *
 * GENERATED by build.py from src/sections/06-activities.html — edit that file,
 * then re-run `python3 build.py` from the project root.
 *
 * @package BrightSaplings
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>

<!-- ============================================================
     SECTION: Activities
     Needs: src/css/sections/activities.css

     Three layers: the shape of a day, the shape of a week, and
     the themes that change through the year.
     ============================================================ -->
<section class="section" id="activities">
  <div class="wrap">

    <div class="head head--centred reveal">
      <span class="sticker sticker--peach">Every single day</span>
      <h2>There's a rhythm to it.</h2>
      <p>Children settle when they know what comes next. The order of our day
        never changes &mdash; only what we put inside it.</p>
    </div>

    <ul class="rhythm stagger">
      <li><span class="rhythm__dot" aria-hidden="true">1</span> Morning Circle</li>
      <li><span class="rhythm__dot" aria-hidden="true">2</span> Story Time</li>
      <li><span class="rhythm__dot" aria-hidden="true">3</span> Music &amp; Movement</li>
      <li><span class="rhythm__dot" aria-hidden="true">4</span> ABC Adventure</li>
      <li><span class="rhythm__dot" aria-hidden="true">5</span> Number Ninjas</li>
      <li><span class="rhythm__dot" aria-hidden="true">6</span> Discovery Time</li>
      <li><span class="rhythm__dot" aria-hidden="true">7</span> Creative Corner</li>
      <li><span class="rhythm__dot" aria-hidden="true">8</span> Outdoor Explorers</li>
      <li><span class="rhythm__dot" aria-hidden="true">9</span> Quiet Time</li>
      <li><span class="rhythm__dot" aria-hidden="true">10</span> Learning Centers</li>
    </ul>

    <div class="reveal">
      <h3 class="sub-head">And every day of the week has its own flavour.</h3>
      <p>So a Tuesday feels different from a Thursday, and children start looking
        forward to things.</p>
    </div>

    <div class="week-themes stagger">
      <article class="wtheme">
        <p class="wtheme__day">Monday</p>
        <h3>Colorful Creations</h3>
        <ul>
          <li>Wear the colour of the week</li>
          <li>Rainbow fruit or vegetable tasting</li>
          <li>Colour matching games</li>
          <li>Finger painting</li>
          <li>A book about colours</li>
        </ul>
      </article>

      <article class="wtheme">
        <p class="wtheme__day">Tuesday</p>
        <h3>Tasty Tuesday</h3>
        <ul>
          <li>Taste a new fruit or vegetable</li>
          <li>Simple no-bake cooking</li>
          <li>Where food comes from</li>
          <li>Practising table manners</li>
          <li>Talking about healthy foods</li>
        </ul>
      </article>

      <article class="wtheme">
        <p class="wtheme__day">Wednesday</p>
        <h3>Wonder Wednesday</h3>
        <ul>
          <li>Nature walk</li>
          <li>Gardening and watering plants</li>
          <li>Leaf and flower crafts</li>
          <li>Bug hunt</li>
          <li>Outdoor science</li>
        </ul>
      </article>

      <article class="wtheme">
        <p class="wtheme__day">Thursday</p>
        <h3>Creative Kids</h3>
        <ul>
          <li>Painting</li>
          <li>Play-Doh creations</li>
          <li>Music and dance</li>
          <li>Dress-up station</li>
          <li>Puppet show</li>
        </ul>
      </article>

      <article class="wtheme">
        <p class="wtheme__day">Friday</p>
        <h3>Fun Friday</h3>
        <ul>
          <li>Dance party</li>
          <li>Show &amp; Tell</li>
          <li>Bubble party</li>
          <li>Picnic lunch outside</li>
          <li>Pyjama day, once a month</li>
        </ul>
      </article>
    </div>

    <div class="reveal">
      <h3 class="sub-head">Then the seasons turn.</h3>
      <p>Each month has a learning focus, so topics build on one another instead
        of arriving at random.</p>
    </div>

    <div class="season-grid stagger">
      <div class="season-card">
        <h3>🌸 Spring Into Learning</h3>
        <ul>
          <li>Flowers</li>
          <li>Butterflies</li>
          <li>Rainbows</li>
          <li>Gardening</li>
        </ul>
      </div>
      <div class="season-card">
        <h3>☀️ Summer Adventures</h3>
        <ul>
          <li>Ocean week</li>
          <li>Camping week</li>
          <li>Beach week</li>
          <li>Ice cream social</li>
        </ul>
      </div>
      <div class="season-card">
        <h3>🍂 Fall Fun</h3>
        <ul>
          <li>Apples</li>
          <li>Pumpkins</li>
          <li>Leaves</li>
          <li>Harvest</li>
        </ul>
      </div>
      <div class="season-card">
        <h3>❄️ Winter Wonders</h3>
        <ul>
          <li>Snow</li>
          <li>Penguins</li>
          <li>Polar bears</li>
          <li>Kindness week</li>
        </ul>
      </div>
    </div>

    <div class="reveal">
      <h3 class="sub-head">And some weeks we throw the timetable out.</h3>
      <p>A rotating set of special weeks and days that children remember long
        after they've moved on to kindergarten.</p>
    </div>

    <ul class="special stagger">
      <li>📚 Storybook Day</li>
      <li>🧸 Teddy Bear Picnic</li>
      <li>👨‍🍳 Little Chef Day</li>
      <li>🚒 Community Helper Week</li>
      <li>🚜 Farm Week</li>
      <li>🦕 Dinosaur Discovery Week</li>
      <li>🐠 Under the Sea Week</li>
      <li>🚀 Space Exploration Week</li>
      <li>🐛 Bug Safari Week</li>
      <li>🦋 Butterfly Garden Week</li>
      <li>🎪 Carnival Day</li>
      <li>🧩 STEM Exploration Day</li>
      <li>🎵 Music Festival Day</li>
      <li>🎈 Birthday Celebration Friday</li>
    </ul>

    <p class="note-line reveal" style="margin-top:26px">
      Birthdays are celebrated together on the last Friday of the month, so every
      child gets a party.
    </p>

  </div>
</section>
