<?php
/**
 * Section: Programs
 *
 * GENERATED by build.py from src/sections/05-programs.html — edit that file,
 * then re-run `python3 build.py` from the project root.
 *
 * @package BrightSaplings
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>

<!-- ============================================================
     SECTION: Programs
     Needs: src/css/sections/programs.css
     ============================================================ -->
<section class="section section--oat" id="programs">
  <div class="wrap">

    <div class="head head--centred reveal">
      <span class="sticker">Two groups</span>
      <h2>Toddlers and preschoolers, under one roof.</h2>
      <p>Children move up when they're ready, not on a birthday, and they
        share the same table, the same yard and the same grown-ups the whole way
        through.</p>
    </div>

    <div class="cards cards--2 stagger">

      <article class="card card--program" data-tilt>
        <div class="card__media">
          <!-- IMAGE: images/program-toddler.jpg (900x560) -->
          <div class="img-ph img-ph--wide" aria-hidden="true">
            <span class="img-ph__label">Toddlers photo</span>
            <span class="img-ph__hint">images/program-toddler.jpg</span>
          </div>
        </div>
        <div class="card__body">
          <span class="tag">18 months to 3 years</span>
          <h3>Toddlers</h3>
          <p>Big feelings, small hands. This is the year for words, for routine,
            and for learning that waiting is survivable.</p>
          <ul class="mini-list">
            <li>Potty learning at your child's own pace</li>
            <li>Music, messy play and long stretches outside</li>
            <li>Language and early social skills all day</li>
          </ul>
          <p class="card__foot">Full day <b>8&ndash;6</b></p>
        </div>
      </article>

      <article class="card card--program" data-tilt>
        <div class="card__media">
          <!-- IMAGE: images/program-preschool.jpg (900x560) -->
          <div class="img-ph img-ph--wide" aria-hidden="true">
            <span class="img-ph__label">Preschool photo</span>
            <span class="img-ph__hint">images/program-preschool.jpg</span>
          </div>
        </div>
        <div class="card__body">
          <span class="tag">3 to 5 years</span>
          <h3>Preschool</h3>
          <p>Kindergarten readiness without a single worksheet. Letters and
            numbers turn up inside projects, cooking and building.</p>
          <ul class="mini-list">
            <li>Pre-literacy and early maths, in context</li>
            <li>ABC Adventure and Number Ninjas every week</li>
            <li>Getting ready for the jump to kindergarten</li>
          </ul>
          <p class="card__foot">Full day <b>8&ndash;6</b></p>
        </div>
      </article>

    </div>
  </div>
</section>
